export const InvoiceHeader:{
  lines: {
    /*InvoiceHeaderID:	number,
    AppendixNo:	string,
    CustomerID:	number,
    CreditorAccountNo:	string,
    VendorName:	string,
    SellersInvoiceID:	string,
    BuyersOrderID:	string,
    BuyersContactID:	string,
    SellersOrderID:	string,
    IssueDate:	Date,
    ImportedDate:	Date,
    BuyersReferenceSchemeID:	string,
    BuyersReferenceID:	number,
    SellersTaxID:	string,
    PaymentDueDate:	Date,
    TypeCode:	string,
    TaxAmount:	number,
    TotalAmount:	number,
    Currency:	string,
    UserID:	number,
    BasePath:	string,
    InvoiceUniqueID:	string,
    DocumentPreview:	string,
    DocumentName:	string,
    CounterBalanceInvoiceID:	number,
    HasCreditorMatch:	boolean,
    NoVendor:	boolean,
    Distributed:	boolean,
    Accounted:	boolean,
    Approved:	boolean,
    PaymentApproved:	boolean,
    Released:	boolean,
    DeletedByID:	number,
    DeclinedByID:	number,
    DistributedByID:	number,
    AccountedByID:	number,
    ApprovedByID:	number,
    SecondApprovedByID:	number,
    ReleasedByID:	number,
    PaymentApprovedByID:	number,
    DeletedDate:	Date,
    DeclinedDate:	Date,
    DistributedDate:	Date,
    AccountedDate:	Date,
    ApprovedDate:	Date,
    ReleasedDate:	Date,
    PaymentApprovedDate:	Date,
    LastEditedDate:	Date,
    Exported:	boolean,
    Export:	boolean,
    PaymentWashed:	boolean,
    VendorWashed:	boolean,
    VendorChanged:	boolean,
    Notified:	boolean,
    Reason:	string,
    Type:	string,
    XSLversion:	string,
    XSLprintVersion:	string,
    State:	boolean,
    ExportFailed:	boolean,
    ExportID:	number,
    ExportedBackup:	boolean,
    ExternalAppendixNo:	string*/
  }[]
} = {
  lines: [
      {InvoiceHeaderID: 2627221,}// AppendixNo: "6652",	CustomerID: 320, 	CreditorAccountNo: "31961661",	VendorName: "DIGISENSE A/S - TEST",	SellersInvoiceID: "20200828_TEST1",	BuyersOrderID: "1", 	BuyersContactID: "", 	SellersOrderID: '',	IssueDate: new Date("2020-08-28 0:00:00"),	ImportedDate: new Date("2020-08-28 11:55:58"), 	BuyersReferenceSchemeID: "EAN",	BuyersReferenceID: 5790002421167,	SellersTaxID: '101011978',	PaymentDueDate: new Date("2020-09-11 0:00:00"),	TypeCode: 'PIE', 	TaxAmount: 250000000,	TotalAmount: 1250000000, Currency: 'DKK',	UserID: 4943,	BasePath: "C:\Users\Christoffer\Dropbox\Ervherv\Digisense AS\Kildekoder\ImportDocuments\Testmiljø\Storage\5790002421167\PIE", InvoiceUniqueID: '20200828115557.394165.fakturaportal', 	DocumentPreview: '20200828115557.394165.fakturaportal',	DocumentName: '20200828115557.394165.fakturaportal.dat',	CounterBalanceInvoiceID: 0, 	HasCreditorMatch: true, 	NoVendor: false,	[Distributed]: 1, 	Accounted: true,  	Approved: true, 	PaymentApproved: false,	Released: false, 	DeletedByID: 0,	DeclinedByID: 0,	DistributedByID: 0,	AccountedByID: 4264,	ApprovedByID: 4123, 	SecondApprovedByID: 0, 	ReleasedByID: 0,	PaymentApprovedByID: 0,	DeletedDate: new Date(''), 	DeclinedDate: new Date(''),	DistributedDate: new Date(''),	AccountedDate: new Date("2020-08-28 12:49:17"),	ApprovedDate: new Date("2020-08-28 12:49:17"),	ReleasedDate: new Date("2020-08-28 12:40:55"),	PaymentApprovedDate: new Date(''),	LastEditedDate: new Date("2020-08-28 12:49:27"),	Exported: false,	Export: false,	PaymentWashed: false,	VendorWashed: false,	VendorChanged: false,	Notified: false, 	Reason: '',	Type: 'COST',	XSLversion: 'fc30R01.xsl',	XSLprintVersion: 'fc30R01_print.xsl',	State: false,	ExportFailed: false,	ExportID: 0,	ExportedBackup: false,	ExternalAppendixNo: '10'}
      
  ]
};

export default InvoiceHeader;